Repository prgrms-web-devcourse/Team-10jo-10wonmoa-FE, pull requests merged in 2022-08, with the labels that each got.

#79 Feat/#75 가계부 일일 페이지 추가 작업
  src/components/BottomNavigation.tsx
  src/components/RoundButton.tsx
  src/components/account/AccountBookDailyCard.tsx
  src/components/account/AccountBookDailyItem.tsx
  src/components/account/AccountBookDailySum.tsx
  src/components/account/TabsDisplayAccountSum.tsx
  src/components/index.ts
  src/components/layout/AppLayout.tsx
  src/components/layout/LoginLayout.tsx
  src/hooks/useMonthSelector.ts
  src/pages/accountBook/index.tsx
  src/pages/accountBookDaily/index.tsx
Labels: 페이지

#87 Refactor/#86 mosnSelector dayjs 라이브러리 사용버전으로 컨버팅
  package.json
  src/.env
  src/api/core/index.ts
  src/api/users.ts
  src/components/Input.tsx
  src/components/MonthSelector.tsx
  src/hooks/useMonthSelector.ts
  src/pages/accountBook/index.tsx
  src/pages/accountBookDaily/index.tsx
  src/pages/login/index.tsx
  src/pages/signUp/index.tsx
  yarn.lock
Labels: 컴포넌트

#89 Feature/#85 Loading 컴포넌트 구현
  src/App.tsx
  src/components/Loading.tsx
  src/components/index.ts
  src/components/layout/AppLayout.tsx
Labels: 프론트

#94 Fix/#93 bottom navigation bar
  src/assets/Icon/AccountBook.svg
  src/assets/Icon/Budget.svg
  src/assets/Icon/Home.svg
  src/assets/Icon/Profile.svg
  src/components/BottomNavigation.tsx
  src/components/Destination.tsx
Labels: 컴포넌트

#96 Feat/#90 react query error
  src/hooks/useApiError.ts
  src/index.tsx
  src/router/index.tsx
Labels: 환경설정

#97 Feature/#88 로그인, 회원가입 API 연결
  src/api/react-query/constant.ts
  src/hooks/auth/useAuth.ts
  src/models/User.ts
  src/models/index.ts
  src/pages/login/components/LoginForm.tsx
  src/pages/login/index.tsx
  src/pages/signUp/components/SignUpForm.tsx
  src/pages/signUp/index.tsx
  src/types/index.ts
  tsconfig.paths.json
Labels: API연결

#102 Refactor/#101 query client 세팅
  .gitignore
  src/.env
  src/App.tsx
  src/api/core/index.ts
  src/api/react-query/queryClient.ts
Labels: 환경설정

#104 Feature/#40 MonthSelector에 Year 추가
  src/hooks/useMonthSelector.ts
  src/pages/accountBook/index.tsx
  src/pages/statistic/index.tsx
  src/utils/formatter/index.ts
Labels: 컴포넌트

#103 Feature/#76 NotFound 페이지 추가
  src/pages/index.ts
  src/pages/notFound/index.tsx
  src/router/index.tsx
Labels: 페이지

#106 Feature/#105 statics tab
  src/components/Tabs.tsx
  src/constants/Tabs.ts
  src/pages/statistic/index.tsx
  src/types/index.ts
  tsconfig.paths.json
Labels: 컴포넌트

#111 Feature/#81 budgetitem
  src/pages/budget/components/BudgetItem.tsx
Labels: 컴포넌트

#109 Feature/#90 error handling
  src/App.tsx
  src/api/react-query/queryClient.ts
  src/hooks/useApiError.ts
  src/types/index.ts
Labels: 환경설정

#110 Feature/#98 가계부 일일 페이지 API 연결 및 관련 기타 작업
  src/api/react-query/constant.ts
  src/components/GoTopButton.tsx
  src/components/Loading.tsx
  src/components/Spinner.tsx
  src/components/account/AccountBookDailyCard.tsx
  src/components/account/AccountBookDailyItem.tsx
  src/components/account/AccountBookDailySum.tsx
  src/components/account/TabsDisplayAccountSum.tsx
  src/components/index.ts
  src/hooks/account/index.ts
  src/hooks/account/useAccountBookDaily.ts
  src/hooks/account/useAccountBookSum.ts
  src/hooks/useMonthSelector.ts
  src/pages/account/index.tsx
  src/pages/accountBook/index.tsx
  src/pages/accountBookDaily/index.tsx
  src/types/accoutBook.d.ts
  src/utils/formatter/dateFormatter.ts
Labels: 페이지

#113 Feature/#80 수입/지출 등록, 수정, 삭제 기능 구현
  .editorconfig
  src/api/account.ts
  src/components/Tabs.tsx
  src/components/account/AccountForm.tsx
  src/components/account/CategoryBox.tsx
  src/hooks/useFormatAmount.ts
  src/models/Account.ts
  src/models/Category.ts
  src/models/index.ts
  src/pages/createAccount/index.tsx
  src/pages/index.ts
  src/pages/statistic/index.tsx
  src/pages/updateAccount/index.tsx
  src/router/index.tsx
  src/types/index.ts
  src/utils/formatter/amountToNumberFormatter.ts
  src/utils/formatter/currencyFormatter.ts
  src/utils/formatter/index.ts
Labels: 프론트, API연결, 기능 추가

#115 Feature/#112 무한스크롤 작업 진행
  src/components/BottomNavigation.tsx
  src/components/account/AccountBookDailyCard.tsx
  src/components/account/AccountBookDailyItem.tsx
  src/hooks/account/useAccountBookDaily.ts
  src/hooks/account/useAccountBookSum.ts
  src/pages/accountBookDaily/index.tsx
  src/types/accoutBook.d.ts
Labels: 기능 추가

#124 Feature/#123 가계부 월간 - 주별 조회 페이지 API 연결
  src/api/react-query/constant.ts
  src/components/DateSelector.tsx
  src/components/TopNavMonthSelector.tsx
  src/components/index.ts
  src/hooks/account/index.ts
  src/hooks/account/useAccountBookMonthly.ts
  src/hooks/account/useAccountBookSum.ts
  src/pages/accountBook/index.tsx
  src/pages/accountBookDaily/index.tsx
  src/pages/accountBookMonthly/index.tsx
  src/pages/statistic/index.tsx
  src/types/accoutBook.d.ts
Labels: 페이지, API연결

#131 Feature/#130 존재하지않는 url 접근시 유저에게 NotFound 페이지를 보여줌
  src/router/index.tsx
Labels: 라우팅

#132 Feature/#129 로그인 회원가입 UseMutaion 적용 및 UI 수정
  src/components/Divider.tsx
  src/components/Input.tsx
  src/components/SubTitle.tsx
  src/components/auth/AuthFormWrapper.tsx
  src/components/auth/ErrorParagraph.tsx
  src/components/auth/LoginForm.tsx
  src/components/auth/SignUpForm.tsx
  src/components/auth/SubTitle.tsx
  src/components/auth/Title.tsx
  src/components/auth/TitleSection.tsx
  src/components/auth/index.ts
  src/components/index.ts
  src/components/layout/LoginLayout.tsx
  src/hooks/auth/useAuth.ts
  src/hooks/auth/useLogin.ts
  src/hooks/auth/useSignUp.ts
  src/pages/login/index.tsx
  src/pages/signUp/index.tsx
Labels: 페이지, 리팩터링

#121 Feature/#108 통계 페이지 원 그래프 제작(타입 미완성)
  src/components/DropDown.tsx
  src/components/statistic/PieChart.tsx
  src/components/statistic/StatisticItem.tsx
  src/pages/statistic/DummyData.js
  src/pages/statistic/index.tsx
Labels: 리뷰 요청, 페이지

#138 Fix/#137 인증 필요, 불필요 분리를 위한 토큰 로직 수정
  src/api/account.ts
  src/api/core/index.ts
  src/api/users.ts
  src/hooks/account/useAccountBookDaily.ts
  src/hooks/account/useAccountBookMonthly.ts
  src/hooks/account/useAccountBookSum.ts
  src/hooks/auth/useLogin.ts
  src/hooks/auth/useSignUp.ts
Labels: FIX

#141 Feature/#135 통계 페이지 API 연결
  src/components/DropDown.tsx
  src/components/statistic/StatisticItem.tsx
  src/components/statistic/TopNabMonthWithDropDown.tsx
  src/components/statistic/index.ts
  src/hooks/statistics/useStatistic.ts
  src/pages/statistic/DummyData.js
  src/pages/statistic/index.tsx
  src/types/statistics.d.ts
Labels: API연결, UI

#140 Feature/#134 가계부 일일, 월간 조회 페이지 UI
  src/components/Divider.tsx
  src/components/TopNavMonthSelector.tsx
  src/components/TopNavOutline.tsx
  src/components/account/AccountBookDailyCard.tsx
  src/components/account/AccountBookDailyItem.tsx
  src/components/account/AccountBookDailySum.tsx
  src/components/account/AccountBookMonthlyCard.tsx
  src/components/account/TabsDisplayAccountSum.tsx
  src/components/account/TabsNavigation.tsx
  src/components/account/index.ts
  src/hooks/account/useAccountBookDaily.ts
  src/pages/accountBook/index.tsx
  src/pages/accountBookDaily/index.tsx
  src/pages/accountBookMonthly/index.tsx
Labels: 페이지, UI

#143 Feature/#142 400 error
  src/hooks/useApiError.ts
  src/mocks/handler.ts
  src/mocks/handlers/Error.ts
Labels: 기능 추가

#145 Feature/#122 예산 조회페이지
  src/api/budget.ts
  src/mocks/handler.ts
  src/mocks/handlers/Budget.ts
  src/pages/budget/components/BudgetItem.tsx
  src/pages/budget/index.tsx
  src/types/budget.ts
Labels: 페이지, API연결

#146 Feature/#114 검색 페이지 구현
  src/api/account.ts
  src/components/CheckBox.tsx
  src/components/Toggle.tsx
  src/components/TopNavOutline.tsx
  src/components/account/AccountForm.tsx
  src/components/index.ts
  src/components/search/CategoryModal.tsx
  src/components/search/SearchForm.tsx
  src/components/search/SearchResultAccountItem.tsx
  src/components/search/index.ts
  src/constants/Tabs.ts
  src/pages/createAccount/index.tsx
  src/pages/index.ts
  src/pages/search/index.tsx
  src/pages/updateAccount/index.tsx
  src/router/index.tsx
  src/styles/emotion.d.ts
  src/styles/theme.ts
  src/types/index.ts
Labels: 페이지, 컴포넌트

#149 Feature/#139 프로필페이지
  src/api/users.ts
  src/assets/Icon/Profile.svg
  src/components/BottomNavigation.tsx
  src/components/Destination.tsx
  src/pages/index.ts
  src/pages/profile/index.tsx
  src/router/index.tsx
Labels: 라우팅, 페이지

#147 Feat/#134 구글 로그인 및 Oauth 처리
  src/assets/Icon/btn_google_light_normal_ios.svg
  src/components/Button.tsx
  src/components/account/AccountForm.tsx
  src/components/auth/LoginForm.tsx
  src/components/auth/SignUpForm.tsx
  src/pages/OAuth2RedirectHandler/index.tsx
  src/pages/index.ts
  src/pages/login/index.tsx
  src/router/index.tsx
Labels: 페이지, UI

#156 Feature/#139 프로필페이지
  src/api/users.ts
  src/pages/profile/index.tsx
Labels: 페이지, API연결

#155 Feature/#154 예산페이지
  src/api/budget.ts
  src/pages/budget/BudgetEdit.tsx
  src/pages/budget/components/BudgetEditItem.tsx
  src/pages/budget/components/BudgetItem.tsx
  src/pages/budget/index.tsx
  src/pages/index.ts
  src/types/budget.ts
Labels: 페이지, API연결

#158 Feature/#157 private라우트
  src/router/PrivateRoute.tsx
  src/router/index.tsx
Labels: 페이지

#159 Feature/#152 AccessToken 재발급
  src/api/account.ts
  src/api/auth.ts
  src/api/budget.ts
  src/api/core/index.ts
  src/api/users.ts
  src/components/auth/LoginForm.tsx
  src/components/auth/SignUpForm.tsx
  src/hooks/account/useAccountBookDaily.ts
  src/hooks/account/useAccountBookMonthly.ts
  src/hooks/account/useAccountBookSum.ts
  src/hooks/account/useCalendar.ts
  src/hooks/auth/useLogin.ts
  src/hooks/auth/useSignUp.ts
  src/hooks/statistics/useStatistic.ts
  src/pages/login/index.tsx
  src/pages/signUp/index.tsx
  src/types/index.ts
  src/types/user.d.ts
Labels: 기능 추가

#161 Feature/#160 Toast 컴포넌트 추가
  package.json
  src/App.tsx
  src/components/Toast.tsx
  src/components/index.ts
  src/components/search/CategoryModal.tsx
  src/hooks/auth/useLogin.ts
  src/hooks/auth/useSignUp.ts
  src/hooks/useApiError.ts
  src/pages/OAuth2RedirectHandler/index.tsx
  src/pages/accountBookCalendar/index.tsx
  src/pages/createAccount/index.tsx
  src/pages/updateAccount/index.tsx
  yarn.lock
Labels: 컴포넌트

#168 Fix/#167 예산페이지
  src/api/budget.ts
  src/router/index.tsx
Labels: 라우팅, FIX

#170 Design/#169 AppLayout 및 reset.css 수정
  src/components/Tabs.tsx
  src/components/TopNavBar.tsx
  src/components/layout/AppLayout.tsx
  src/styles/reset.ts
Labels: UI

#172 Feature/#171 금액 포매팅 함수 suffix 옵셔널 parameter 추가
  src/utils/formatter/currencyFormatter.ts
Labels: 기능 추가

#176 Fix/#165 달력 페이지 드래그 이벤트 방지
  src/pages/accountBookCalendar/index.tsx
  src/pages/accountBookCalendar/makeCalendarData.ts
Labels: FIX

#178 fix: private route 제거
  src/router/PrivateRoute.tsx
  src/router/index.tsx
Labels: FIX

#175 Design/#162 가계부페이지 UI 수정
  src/assets/PaperPlane.png
  src/components/Divider.tsx
  src/components/GoTopButton.tsx
  src/components/account/AccountBookDailySum.tsx
  src/components/account/AccountBookEmpty.tsx
  src/components/account/AccountBookMonthlyCard.tsx
  src/components/account/PlusButton.tsx
  src/components/account/index.ts
  src/hooks/account/useAccountBookDaily.ts
  src/hooks/account/useAccountBookMonthly.ts
  src/pages/accountBook/index.tsx
  src/pages/accountBookDaily/index.tsx
  src/pages/accountBookMonthly/index.tsx
  src/utils/formatter/dateFormatter.ts
Labels: UI

#180 design: 폰트사이즈 정의
  src/styles/emotion.d.ts
  src/styles/theme.ts
Labels: UI

#182 Feature/#174 수입,지출 등록 수정 페이지 카테고리 모달 적용
  src/components/CheckBox.tsx
  src/components/Radio.tsx
  src/components/Tabs.tsx
  src/components/account/AccountForm.tsx
  src/components/index.ts
  src/components/search/CategoryModal.tsx
  src/components/search/CheckBoxList.tsx
  src/components/search/RadioList.tsx
  src/components/search/SearchForm.tsx
  src/components/search/index.ts
  src/pages/createAccount/index.tsx
  src/pages/search/index.tsx
  src/pages/updateAccount/index.tsx
Labels: 기능 추가

#185 Design/#153 통계 스타일 수정
  src/components/DropDown.tsx
  src/components/Tabs.tsx
  src/components/statistic/PieChart.tsx
  src/components/statistic/StatisticItem.tsx
  src/components/statistic/TopNabMonthWithDropDown.tsx
  src/pages/statistic/index.tsx
  src/pages/statistic/makePieData.ts
Labels: UI

#183 Feature/#181 예산 페이지 , 네비게이션바
  src/api/budget.ts
  src/components/BottomNavigation.tsx
  src/components/Destination.tsx
  src/pages/accountBookDaily/index.tsx
  src/pages/budget/BudgetEdit.tsx
  src/pages/budget/components/BudgetEditItem.tsx
  src/pages/budget/components/BudgetItem.tsx
  src/pages/budget/index.tsx
  src/styles/animation.ts
  src/styles/emotion.d.ts
  src/styles/reset.ts
  src/styles/theme.ts
  src/types/budget.ts
Labels: 페이지, 컴포넌트, 리팩터링, UI

#184 Feature/#148 검색 페이지 무한스크롤 구현
  src/api/account.ts
  src/components/Spinner.tsx
  src/components/search/CategoryModal.tsx
  src/components/search/SearchResultEmpty.tsx
  src/components/search/index.ts
  src/pages/createAccount/index.tsx
  src/pages/search/index.tsx
  src/pages/updateAccount/index.tsx
Labels: 기능 추가

#190 Fix/#189 모바일 대응 및 버그 수정
  src/App.tsx
  src/components/BackupLayer.tsx
  src/components/Tabs.tsx
  src/components/layout/AppLayout.tsx
  src/components/search/CategoryModal.tsx
  src/components/search/SearchForm.tsx
  src/index.tsx
  src/styles/reset.ts
Labels: FIX

#194 Fix/#188 달력, 통계 페이지 버그, UI 수정
  public/favicon.ico
  src/pages/accountBookCalendar/index.tsx
  src/pages/statistic/index.tsx
  src/pages/statistic/makePieData.ts
Labels: UI, FIX

#197 Fix/#195 브라우저 리사이징 시 vh 계산, 스토리북 패키지 삭제
  .storybook/main.js
  .storybook/preview.js
  package-lock.json
  package.json
  src/App.tsx
  src/hooks/index.ts
  src/hooks/useLayoutResize.ts
  src/index.tsx
  src/stories/components/AppLayout.stories.tsx
  yarn.lock
Labels: FIX

#199 Fix/#198 가계부 일일페이지 로딩 오류 수정
  src/pages/accountBookDaily/index.tsx
Labels: FIX

#205 Fix/#204 구글 아이콘 수정
  src/assets/Icon/GoogleIcon.svg
  src/assets/Icon/btn_google_light_normal_ios.svg
  src/assets/googleIcon.png
  src/components/auth/LoginForm.tsx
Labels: UI, FIX

#202 feat: 맨처음 들어왔을때 보여줄 로고페이지
  src/pages/index.ts
  src/pages/logo/index.tsx
  src/router/index.tsx
  src/styles/animation.ts
  src/styles/reset.ts
Labels: 라우팅, 페이지

#201 Fix/#191 모바일 대응 기타 스타일 수정
  src/components/Tabs.tsx
  src/components/account/AccountForm.tsx
  src/components/search/SearchForm.tsx
  src/components/search/SearchResultAccountItem.tsx
  src/styles/reset.ts
Labels: FIX

#207 Design/#206 통계 색상, 달력 폰트 사이즈 조정
  src/pages/accountBookCalendar/index.tsx
  src/pages/statistic/index.tsx
Labels: UI

#210 Fix/#209 예산설정페이지
  README.md
  src/pages/budget/BudgetEdit.tsx
  src/pages/budget/index.tsx
  src/router/index.tsx
  src/styles/emotion.d.ts
Labels: 페이지, FIX

#214 Fix/#211 메인 Redirect 주소 수정 - 로그인, NotFound, Oauth
  src/hooks/auth/useLogin.ts
  src/pages/OAuth2RedirectHandler/index.tsx
  src/pages/notFound/index.tsx
Labels: FIX

#213 Fix/#212 네비게이션바 아이콘 활성화
  src/components/BottomNavigation.tsx
Labels: UI

#216 Fix/#215 예산페이지 날짜에 맞게 url 변경
  src/pages/budget/index.tsx
Labels: 라우팅

#219 Fix/#218 라우터 queryString, dateSelector 컴포넌트 싱크 오류
  src/hooks/useMonthSelector.ts
  src/pages/accountBook/index.tsx
Labels: FIX

#208 [Release] 최종 발표 전 UI 수정사항 및 버그 반영 release
  .storybook/main.js
  .storybook/preview.js
  README.md
  package-lock.json
  package.json
  public/favicon.ico
  src/App.tsx
  src/api/users.ts
  src/assets/Icon/GoogleIcon.svg
  src/assets/Icon/btn_google_light_normal_ios.svg
  src/assets/googleIcon.png
  src/components/BackupLayer.tsx
  src/components/BottomNavigation.tsx
  src/components/DropDown.tsx
  src/components/Tabs.tsx
  src/components/account/AccountForm.tsx
  src/components/auth/LoginForm.tsx
  src/components/layout/AppLayout.tsx
  src/components/search/CategoryModal.tsx
  src/components/search/SearchForm.tsx
  src/components/search/SearchResultAccountItem.tsx
  src/hooks/auth/useLogin.ts
  src/hooks/index.ts
  src/hooks/useLayoutResize.ts
  src/hooks/useMonthSelector.ts
  src/pages/OAuth2RedirectHandler/index.tsx
  src/pages/accountBook/index.tsx
  src/pages/accountBookCalendar/index.tsx
  src/pages/accountBookDaily/index.tsx
  src/pages/budget/BudgetEdit.tsx
  src/pages/budget/index.tsx
  src/pages/index.ts
  src/pages/logo/index.tsx
  src/pages/notFound/index.tsx
  src/pages/profile/components/PasswordCheck.tsx
  src/pages/profile/index.tsx
  src/pages/statistic/index.tsx
  src/pages/statistic/makePieData.ts
  src/router/index.tsx
  src/stories/components/AppLayout.stories.tsx
  src/styles/animation.ts
  src/styles/emotion.d.ts
  src/styles/reset.ts
  yarn.lock
Labels: RELEASE
